name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: write
  id-token: write
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Release
        uses: HRM/github-action-npm-release@2.0.5
        with:
          path: 'packages/form-generator/package.json'
        id: release
      - uses: actions/setup-node@v4
        if: steps.release.outputs.released == 'true'
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --workspace=vue-form-gen"
        if: steps.release.outputs.released == 'true'
      - run: npm run build --workspace=vue-form-gen"
        if: steps.release.outputs.released == 'true'
      - run: npm publish --provenance --access public --workspace=vue-form-gen"
        if: steps.release.outputs.released == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}